### PR TITLE
VEG-131 Pagination

### PR DESCRIPTION
**Pull request by ghost**
Added pagination to the lists in the following components (visible via the respective routes)
- `HistoryDetails`
  - `/history/:id` (Home > Vorherige Einkäufe > Details)
- `HistoryOverview`
  - `/history` (Home > Vorherige Einkäufe)
- `BalanceOverview`
  - `/reports/balance-overview` (Home > Reports > Guthaben-Übersicht)
- `SoldItems`
  - `/reports/sold-items` (Home > Reports > Was wurde gekauft?)
- `ShoppingCartItems`
  - `/shopping/cart` (Home > Warenkorb)
- `StockList`
  - `/shopping/stock` (Home > Einkaufen)
  - `/stock` (Home > Bestand)
- `/routes/users` (Home > Benutzerverwaltung)

Lists with small entries show 10 items, lists with large entries show 5 items.

### CODE REVIEW

**Review by manuel3108 — CHANGES_REQUESTED** [review]
Thanks for the PR!

I generally like the idea that you are differentiating between Lists with large and lists with small content. I think this is a really good improvement for our frontend.

But I have one thing that confuses me:
Why are you loading the full list of i.e. the purchase history and then only apply the paging in the frontend. In my opinion paging should generally be applied in the backend.
I mean, sure there are places i.e. cartItems where we cannot ask the backend to handle to it, because the backend doesn't knows about the cartItems.
But in my opinion this should work in most other cases.

Also having a look at the current implementation, it would not even be necessary to modify the backend.

In my opinion you could take a deep look at what we have done a few days ago with the balance history. This should be the way we should implement it.

If I missed anything why you have done it this way, just notice me.
Currently I cannot approve this PR, even tho fully functional

**Comment by TatjanaMerkel** [comment]
> Why are you loading the full list of i.e. the purchase history and then only apply the paging in the frontend. In my opinion paging should generally be applied in the backend.
> I mean, sure there are places i.e. cartItems where we cannot ask the backend to handle to it, because the backend doesn't knows about the cartItems.
> But in my opinion this should work in most other cases.
> 
> Also having a look at the current implementation, it would not even be necessary to modify the backend.
> 
> In my opinion you could take a deep look at what we have done a few days ago with the balance history. This should be the way we should implement it.
> 
> If I missed anything why you have done it this way, just notice me.

Thank you for your feedback! After having thought about your concerns and suggestions I have re-considered each pagination and came up with the following results:

- `HistoryDetails`
  - `/history/:id` (Home > Vorherige Einkäufe > Details)
    - No BE pagination can be used for this route as there is no endpoint for a purchase's items. This is no problem as a purchase's items are retrieved all together as part of the purchase.
- `HistoryOverview`
  - `/history` (Home > Vorherige Einkäufe)
    - Indeed, BE pagination should be applicable here. Working on it.
- `BalanceOverview`
  - `/reports/balance-overview` (Home > Reports > Guthaben-Übersicht)
    - BE pagination should be possible here, as well. The respective endpoint delivers the aggregated data (total gross, net, etc.) with each page response. In the rare case of an CSV export, all data would need to be requested.
    - Another suggestion (mentioned elsewhere) was to remove pagination for the reports. Has this been decided on already? I would suggest to keep pagination here as especially the reports' data continue to grow with time and would cause large amounts of network traffic and thus waiting times for the user. Of course, it is no problem to remove pagination.
- `SoldItems`
  - `/reports/sold-items` (Home > Reports > Was wurde gekauft?)
    - BE pagination would be problematic, see below. However, it was suggested to remove pagination here, as well. In this case I agree as the user list will likely stay limited, thus alleviating the urge for pagination. Furthermore, not paginating the users list would allow searching for users via standard search (`Ctrl + F`).
- `ShoppingCartItems`
  - `/shopping/cart` (Home > Warenkorb)
    - No BE pagination possible and required, as you have explained above.
- `StockList`
  - `/shopping/stock` (Home > Einkaufen)
    - BE pagination would be problematic because the FE pages are filtered, in this case even multiple times (soon to consume, in stock, by the top search bar). When requesting a page from the BE and then filtering in the FE, some pages might contain few or even no entries at all. To fill all pages equally, more than the page's items need to be requested. Even worse, to determine the number of pages after filtering all items need to be known. I would suggest to keep the FE pagination for now as all items are available anyway due to the real time search.
  - `/stock` (Home > Bestand)
    - See above (/shopping/stock)
- `/routes/users` (Home > Benutzerverwaltung)
  - See above (/shopping/stock)

**Comment by manuel3108** [comment]
You made really good points there that i have not thought of before. See below for my detailed answers.

- `HistoryDetails`
  - `/history/:id` (Home > Vorherige Einkäufe > Details)
    - Agreed
- `HistoryOverview`
  - `/history` (Home > Vorherige Einkäufe)
    - Agreed
- `BalanceOverview`
  - `/reports/balance-overview` (Home > Reports > Guthaben-Übersicht)
    - I understand the point you are making and would let that open to you. I just want to point out that the we currently plan to have a max. of 50 users. In my opinion we only have one balance item per user, so i think that pagination is urgent here.
    - The decision you are speaking about came in the daily today. We thought that a reports is there to really report what's going on and we would not see it to be split this between multiple pages. An alternative that we did not consider today is to drastically increase the page size, to i.e. 100.
    - => I will let this one open to your decision, do what you personally agree more. But I also want to let you know that the new created report for disposed items (#54) will not have pagination.
- `SoldItems`
  - `/reports/sold-items` (Home > Reports > Was wurde gekauft?)
    - I think you mixed something up here, I don't see what all of this has to do with the user count. But as explained above, pagination for reports is not required for reports anymore
- `ShoppingCartItems`
  - `/shopping/cart` (Home > Warenkorb)
    - Agreed
- `StockList`
  - `/shopping/stock` (Home > Einkaufen)
    - Good point with the search. I would agree to let the pagination be done by the frontend.
    - Maybe it would be good to add a comment in the code somewhere to explain why we decided to go this way.
  - `/stock` (Home > Bestand)
    - See above (/shopping/stock)
- `/routes/users` (Home > Benutzerverwaltung)
  - See above (/shopping/stock)

**Comment by TatjanaMerkel** [comment]
Indeed, I have accidentally switched the descriptions for `BalanceOverview` and `SoldItems`. Nonetheless, I agree that the use of pagination is debatable for the reports. For the sake of consistency with the new report, I have decided to remove the pagination from the existing reports again.

The `HistoryOverview` component uses BE pagination now (similar to the `BalanceHistory` component).

For the `StockList` component I have added a comment describing the rationale behind the FE pagination to the code.

**Review by manuel3108 — APPROVED** [review]

**Comment by manuel3108** [comment]
Fine for me. 

I just added another loader for the purchase history to get closer to the balance history.

Please only merge, after https://github.com/HSRM-Vegetables/myfoodcoop-service/pull/13 has been merged

**Pull request merged**
